# Site settings
url: "https://vgnetwork.xyz/" # the base hostname & protocol for your site
timezone: China/Beijing

title: Vanguard
description: The finest of gaming communities
email: rpmoorey@gmail.com

google_analytics: UA-178119679-1

keep_files: []
exclude: ["*.sublime-project",
          "*.sublime-workspace",
          "_app",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "README"]

# Markdown settings
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false